# .github/workflows/remove-files.yml
# Automated file removal workflow triggered by changes to ops/rm.txt

name: Remove Files

on:
  push:
    paths:
      - 'ops/rm.txt'

permissions:
  contents: write

jobs:
  remove-files:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Remove files and clear list
        run: |
          if [ -s ops/rm.txt ]; then
            while IFS= read -r file; do
              [ -n "$file" ] && rm -f "$file"
            done < ops/rm.txt
            : > ops/rm.txt
          fi

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto: Remove files listed in ops/rm.txt"
