name: Deploy Paper Feed to GitHub Pages

on:
  push:
    # branches:
    #   - main
    paths:
      - 'data/papers.yaml'
      - 'src/scripts/frontend/**'
      - '.github/workflows/deploy_frontend.yaml'
  workflow_dispatch:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate HTML
        run: |
          python scripts.frontend.generate_html \
            --data_path data/papers.yaml \
            --template_path src/scripts/frontend/index.template.html \
            --output_path web/index.html

      - name: Ensure presence of .nojekyll file
        run: touch web/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
