# .github/workflows/download-papers.yml
name: Download Paper Files

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  # First wait for tests to pass
  test:
    uses: ./.github/workflows/test-python.yml@main

  # Then download papers
  download-files:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-base
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      
      - name: Download paper files
        run: python -m scripts.download_papers download --papers_dir=data/papers
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Download papers, render markdown"
          file_pattern: |
            data/papers/**
