# .github/workflows/remove-files.yml
# Automated file removal workflow triggered by changes to ops/rm.txt
# or to this workflow file itself

name: Remove Files

on:
  push:
    paths:
      - 'ops/misc.sh'
      - '.github/workflows/ops-misc.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  remove-files:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Remove files and clear list
        run: |
          source ops/misc.sh && ops/misc.sh < "!#/bin/bash"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: miscellaneous file operation"
