# .github/workflows/process-paper.yml
name: Process New Paper
on:
  workflow_dispatch:
  issues:
    types:
      - opened
      - reopened
      - labeled

jobs:
  process-paper:
    if: contains(github.event.issue.labels.*.name, 'paper')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install llamero pyyaml loguru
      
      - name: Process paper
        run: python scripts/process_paper.py
      
      - name: Close Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: '✅ Paper processed and added to the database. Closing this issue.'
            });
            
            await github.rest.issues.update({
              owner,
              repo,
              issue_number,
              state: 'closed'
            });
