# .github/workflows/process-paper.yml
name: Process New Paper
on:
  workflow_dispatch:
  issues:
    types:
      - opened
      - reopened
      - labeled

jobs:
  process-paper:
    if: contains(github.event.issue.labels.*.name, 'paper')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Close Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const { owner, repo } = context.repo;
              const issue_number = context.issue.number;
              
              console.log(`Processing issue ${issue_number} in ${owner}/${repo}`);
              
              // Add a comment before closing
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: '✅ Paper processed and added to the database. Closing this issue.'
              });
              
              // Close the issue
              await github.rest.issues.update({
                owner,
                repo,
                issue_number,
                state: 'closed'
              });
              
              console.log('Successfully processed and closed issue');
              
            } catch (error) {
              console.log('Error details:', {
                message: error.message,
                status: error.status,
                response: error.response
              });
              core.setFailed(`Action failed: ${error.message}`);
            }
