# .github/workflows/process-events.yml
name: Process Paper Events
on:
  push:
    paths:
      - ".github/workflows/process-events.yml"
      - "src/scripts/process_events.py"
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_call:
  workflow_dispatch:

jobs:
  process-papers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for commits
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      
      - name: Process Events
        id: process
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m scripts.process_events
          EVENTS_PROCESSED=${EVENTS_PROCESSED:-false}
          echo "EVENTS_PROCESSED=${EVENTS_PROCESSED}" >> $GITHUB_OUTPUT

      - name: Conditionally trigger frontend deploy
        if: ${{ steps.process.outputs.EVENTS_PROCESSED == 'true' }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy_frontend.yaml/dispatches \
            -d '{"ref":"${{ github.ref }}"}'
