# .github/workflows/process-paper.yml
name: Process New Paper
on:
  issues:
    types: [opened]

jobs:
  process-paper:
    if: contains(github.event.issue.labels.*.name, 'paper')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Add your processing steps here...
      
      # Close the issue after processing
      - name: Close Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            
            // Add a comment before closing
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: issueNumber,
              body: '✅ Paper processed and added to the database. Closing this issue.'
            });
            
            // Close the issue
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: issueNumber,
              state: 'closed'
            });
